### PR TITLE
update to Nom7

### PR DESCRIPTION
**Pull request by alexkunde**

### CODE REVIEW

**Comment by snaggen** [comment]
I'm not a nom expert, so I can't really help you much there. But let me know when this is ready to be tested on development systems and then I might be able to assist with some real world testing.

**Comment by zuisong** [comment]
https://github.com/adwhit/tokio-stomp/pull/16

Here is a PR that can serve as a reference. If needed, I can submit a new PR to this repository.

**Comment by snaggen** [comment]
@zuisong if you provide a PR, then I can help with testing.

**Comment by zuisong** [comment]
@snaggen 😄
I have created a new PR.  https://github.com/alexkunde/tokio-stomp-2/pull/13

**Comment by snaggen** [comment]
> @snaggen 😄
> I have created a new PR.  https://github.com/alexkunde/tokio-stomp-2/pull/13

Nice, will try it out later today

**Pull request closed without merging**
